feat: Replace AWS S3 buckets with Cloudflare R2 buckets
RaoFoundation/templar pull request #12
Opened 2024-11-13 20:50 UTC by noaonoszko

2024-11-20 10:47 UTC, distributedstatemachine requested changes

2024-11-20 10:47 UTC, distributedstatemachine commented on docs/validator.md
> -- **AWS S3 Credentials and Bucket**: Public read is required, so miners / evaluators can download slices. Please refer to this [guide](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnami
update validator storage docs

2024-11-20 10:47 UTC, distributedstatemachine commented on neurons/miner.py
> +    def commit(self) -> None:
move to a chain.py file in tplr

2024-11-20 10:47 UTC, distributedstatemachine commented on neurons/miner.py
> +    def get_commitment(self, uid: int) -> Bucket:
same as above

2024-11-20 10:47 UTC, distributedstatemachine commented on neurons/validator.py
> +from templar.config import BUCKET_SECRETS
access these through tplr

2024-11-20 10:47 UTC, distributedstatemachine commented on scripts/clean.py
> +    region_name=CF_REGION_NAME,
should we hard code thus to ENAM?

2024-11-20 10:47 UTC, distributedstatemachine commented on src/templar/wandb.py
> +        project=f"{config.project}",
why is this changed?

2024-11-20 13:03 UTC, noaonoszko commented on src/templar/wandb.py
> +        project=f"{config.project}",
Just during development to avoid the wandb errors, undid this change now.

2024-11-20 13:05 UTC, noaonoszko commented on scripts/clean.py
> +    region_name=CF_REGION_NAME,
It is already hard-coded to "enam" (only works with small letters) in `constants.py`. Prefer this way rather than typing it out everywhere in case we want to change it sometime in the future.

2024-11-20 13:20 UTC, noaonoszko commented on docs/validator.md
> -- **AWS S3 Credentials and Bucket**: Public read is required, so miners / evaluators can download slices. Please refer to this [guide](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnami
Why when the validator never uploads anything and doesn't need to handle credentials?

2024-11-20 18:16 UTC, distributedstatemachine commented on docs/validator.md
> -- **AWS S3 Credentials and Bucket**: Public read is required, so miners / evaluators can download slices. Please refer to this [guide](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnami
It helps seed the network and will upload check points for the decay miner

2024-11-21 00:03 UTC, noaonoszko commented on docs/validator.md
> -- **AWS S3 Credentials and Bucket**: Public read is required, so miners / evaluators can download slices. Please refer to this [guide](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnami
@distributedstatemachine should we require validators to have bucket secrets in the env file? Right now the program crashes if this file doesn't exist.

2024-11-25 19:16 UTC, distributedstatemachine approved these changes

2024-11-25 20:14 UTC, merged